/**
 * useResults Hook
 * Manages results display, sharing, and saving
 */

import { useState, useCallback } from 'react';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import * as Clipboard from 'expo-clipboard';
import { Platform } from 'react-native';

export function useResults() {
  const [sharing, setSharing] = useState(false);
  const [saving, setSaving] = useState(false);

  /**
   * Copies text to clipboard
   */
  const copyToClipboard = useCallback(async (text) => {
    try {
      await Clipboard.setString(text);
      return true;
    } catch (error) {
      console.error('Failed to copy to clipboard:', error);
      return false;
    }
  }, []);

  /**
   * Shares text using native sharing
   */
  const shareText = useCallback(async (text, title = 'Arabic Video Translator Results') => {
    try {
      setSharing(true);
      if (Platform.OS === 'web') {
        if (navigator.share) {
          await navigator.share({ title, text });
          setSharing(false);
          return true;
        }
        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'translation_results.txt';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        setSharing(false);
        return true;
      } else {
        const fileUri = FileSystem.documentDirectory + 'translation_results.txt';
        await FileSystem.writeAsStringAsync(fileUri, text, {
          encoding: FileSystem.EncodingType.UTF8,
        });
        const isAvailable = await Sharing.isAvailableAsync();
        if (!isAvailable) {
          throw new Error('Sharing is not available on this device');
        }
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/plain',
          dialogTitle: title,
        });
        await FileSystem.deleteAsync(fileUri, { idempotent: true });
        setSharing(false);
        return true;
      }
    } catch (error) {
      console.error('Failed to share:', error);
      setSharing(false);
      return false;
    }
  }, []);

  /**
   * Saves results to device storage
   */
  const saveResults = useCallback(async (results, filename = 'translation_results.txt') => {
    try {
      setSaving(true);
      const content = formatResultsForSave(results);
      if (Platform.OS === 'web') {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        setSaving(false);
        return null;
      } else {
        const fileUri = FileSystem.documentDirectory + filename;
        await FileSystem.writeAsStringAsync(fileUri, content, {
          encoding: FileSystem.EncodingType.UTF8,
        });
        setSaving(false);
        return fileUri;
      }
    } catch (error) {
      console.error('Failed to save results:', error);
      setSaving(false);
      return null;
    }
  }, []);

  /**
   * Formats results for saving
   */
  const formatResultsForSave = useCallback((results) => {
    let content = '=== Arabic Video Translator Results ===\n\n';
    
    if (results.arabicTranscript) {
      content += '--- Arabic Transcript ---\n';
      content += results.arabicTranscript + '\n\n';
    }
    
    if (results.dutchTranslation) {
      content += '--- Dutch Translation ---\n';
      content += results.dutchTranslation + '\n\n';
    }
    
    if (results.duaResults) {
      content += '--- Dua Extraction ---\n';
      content += results.duaResults + '\n\n';
    }
    
    content += 'Generated by Arabic Video Translator\n';
    return content;
  }, []);

  return {
    sharing,
    saving,
    copyToClipboard,
    shareText,
    saveResults,
    formatResultsForSave,
  };
}

